#!/usr/bin/env python3
"""Generate site/robots.txt, site/sitemap.xml and site/llms.txt from the real data.

Run after site/data/build_data.py, so the counts and dates match what the site serves.
Everything here is derived: nothing is hand-written, so the files cannot go stale
while the data moves. Freshness is a ranking signal for both Google and the AI
engines, and a sitemap that lists a page we no longer serve is worse than no sitemap.

    python3 tooling/seo/build_seo_files.py            # write the three files
    python3 tooling/seo/build_seo_files.py --check    # exit 1 if they are out of date
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SITE = ROOT / "site"
DATA = SITE / "data"
HOST = "https://app.cranesignal.com"

# Pages that belong in the sitemap, with how often they change and how much they
# matter relative to each other. Anything not listed here is deliberately left out:
# 404.html (an error page), master-table.html (a redirect stub), property.html
# (one template behind ?id=, so it has no canonical URL of its own).
CORE_PAGES = [
    ("index.html", "daily", "1.0"),
    ("under-the-hood.html", "monthly", "0.6"),
    ("privacy.html", "yearly", "0.2"),
]

# AI crawlers we want reading the site, named explicitly. There is no robots.txt
# today, which permits everything by default but states nothing; an explicit allow
# is the clearer signal, and it documents the decision for whoever reads it next.
AI_AGENTS = [
    ("GPTBot", "OpenAI, feeds ChatGPT"),
    ("OAI-SearchBot", "OpenAI search"),
    ("ChatGPT-User", "ChatGPT browsing on a user's behalf"),
    ("ClaudeBot", "Anthropic training"),
    ("Claude-SearchBot", "Anthropic search index -- citations in Claude"),
    ("Claude-User", "Claude fetching a page to answer a question right now"),
    ("Claude-Web", "Anthropic, older name"),
    ("anthropic-ai", "Anthropic, older name"),
    ("PerplexityBot", "Perplexity"),
    ("Perplexity-User", "Perplexity browsing on a user's behalf"),
    ("Google-Extended", "Gemini grounding (separate from Googlebot)"),
    ("Applebot-Extended", "Apple Intelligence"),
    ("CCBot", "Common Crawl, which many models train from"),
    ("Bingbot", "Bing, whose index feeds Copilot and ChatGPT search"),
]


def load_areas() -> tuple[dict, list[dict]]:
    index = json.loads((DATA / "areas" / "index.json").read_text(encoding="utf-8"))
    areas = []
    for area in index.get("areas", []):
        if area.get("hidden"):
            continue
        path = DATA / "areas" / f"{area['slug']}.json"
        if not path.exists():
            continue
        payload = json.loads(path.read_text(encoding="utf-8"))
        areas.append({**area, "payload": payload})
    return index, areas


def generated_pages() -> list[tuple[str, str, str]]:
    """The /leads/ pages, discovered rather than assumed.

    The page builder owns which of these exist; we only report what is on disk,
    so adding or dropping a page needs no change here.
    """
    leads = SITE / "leads"
    if not leads.exists():
        return []
    out = []
    for path in sorted(leads.rglob("*.html")):
        rel = path.relative_to(SITE).as_posix()
        depth = rel.count("/")
        # State pages sit at leads/tx.html and outrank the city pages below them.
        priority = "0.9" if depth == 1 else "0.8"
        out.append((rel, "weekly", priority))
    return out


def build_robots() -> str:
    lines = [
        "# CraneSignal -- app.cranesignal.com",
        "# Generated by tooling/seo/build_seo_files.py. Do not edit by hand.",
        "",
        "User-agent: *",
        "Allow: /",
        "",
        "# Nothing here is private, but these paths are not content:",
        "Disallow: /master-table.html",
        "",
        "# Search and answer engines we explicitly welcome.",
    ]
    for agent, why in AI_AGENTS:
        lines += [f"# {why}", f"User-agent: {agent}", "Allow: /", ""]
    lines += [f"Sitemap: {HOST}/sitemap.xml", ""]
    return "\n".join(lines)


def build_sitemap(updated: str) -> str:
    entries = CORE_PAGES + generated_pages()
    out = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by tooling/seo/build_seo_files.py. Do not edit by hand. -->",
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ]
    for rel, changefreq, priority in entries:
        loc = f"{HOST}/{rel}"
        out += [
            "  <url>",
            f"    <loc>{loc}</loc>",
            f"    <lastmod>{updated}</lastmod>",
            f"    <changefreq>{changefreq}</changefreq>",
            f"    <priority>{priority}</priority>",
            "  </url>",
        ]
    out += ["</urlset>", ""]
    return "\n".join(out)


def build_llms(index: dict, areas: list[dict]) -> str:
    updated = index.get("updated", "")
    total = sum(int(a.get("leads") or 0) for a in areas)
    units = sum(int(a["payload"].get("stats", {}).get("unitsInPlay") or 0) for a in areas)

    lines = [
        "# CraneSignal",
        "",
        f"> A free, sourced list of {total:,} apartment buildings in the United States that are "
        f"newly permitted, under construction, or recently sold -- {units:,} units in all. "
        f"Every building links to the public record it came from. Last updated {updated}.",
        "",
        "CraneSignal exists for people who sell to apartment owners: software vendors, service",
        "providers and their sales teams. It answers one question -- which buildings are about to",
        "need something, and why now -- from public records only.",
        "",
        "## What the data is",
        "",
        "Each building carries, where the public record says so: name, street address, city, unit",
        "count, stage (planned, permitted, under construction, leasing or sold), permit date,",
        "expected opening date, sale date, buyer, developer, office phone, and a link to every",
        "source it was found in. Facts without a source are marked unsourced rather than guessed.",
        "",
        "## Where it comes from",
        "",
        "State and city construction records, county appraisal-district sale records, and public",
        "news announcements. No proprietary feeds, no scraped logins, no purchased lists. The",
        "collection is read-only: CraneSignal never posts, votes or submits anything anywhere.",
        "",
        "## Coverage",
        "",
    ]
    for area in areas:
        stats = area["payload"].get("stats", {})
        bits = [f"{int(area.get('leads') or 0):,} buildings"]
        if stats.get("cities"):
            bits.append(f"{stats['cities']} cities")
        if stats.get("unitsInPlay"):
            bits.append(f"{int(stats['unitsInPlay']):,} units")
        lines.append(f"- {area['label']}: {', '.join(bits)}")
    lines += [
        "",
        "## Pages",
        "",
        f"- [Lead list]({HOST}/index.html): every building, filterable by state, with lead scores.",
        f"- [How it works]({HOST}/under-the-hood.html): where each number comes from and how it was tested.",
        f"- [Privacy]({HOST}/privacy.html)",
        f"- [Full data summary]({HOST}/llms-full.txt): every per-place total in one file.",
    ]
    for rel, _, _ in generated_pages():
        lines.append(f"- {HOST}/{rel}")
    lines += [
        "",
        "## Citing this",
        "",
        "Counts change weekly as new records appear. Quote the 'last updated' date with any number.",
        "Building-level claims should link the building's own source record, not this file.",
        "",
    ]
    return "\n".join(lines)


JSONLD_START = "  <!-- SEO-JSONLD:start (written by tooling/seo/build_seo_files.py) -->"
JSONLD_END = "  <!-- SEO-JSONLD:end -->"


def build_jsonld(index: dict, areas: list[dict]) -> str:
    """Organization, WebSite and Dataset for the home page.

    Dataset is the one that earns its keep: it tells both Google and the answer
    engines that this is a maintained collection with a size, a coverage area and a
    date, which is exactly the claim we want them repeating.
    """
    updated = index.get("updated", "")
    total = sum(int(a.get("leads") or 0) for a in areas)
    units = sum(int(a["payload"].get("stats", {}).get("unitsInPlay") or 0) for a in areas)

    graph = [
        {
            "@type": "Organization",
            "@id": f"{HOST}/#org",
            "name": "CraneSignal",
            "url": HOST,
            "description": (
                "Sourced lead data on apartment buildings that are newly permitted, "
                "under construction or recently sold."
            ),
        },
        {
            "@type": "WebSite",
            "@id": f"{HOST}/#site",
            "url": HOST,
            "name": "CraneSignal",
            "publisher": {"@id": f"{HOST}/#org"},
            "inLanguage": "en-US",
        },
        {
            "@type": "Dataset",
            "@id": f"{HOST}/#dataset",
            "name": "CraneSignal apartment construction and sales pipeline",
            "description": (
                f"{total:,} apartment buildings across {len(areas)} US states -- {units:,} units -- "
                "that are planned, permitted, under construction, leasing or recently sold. "
                "Each record carries its public source record."
            ),
            "url": f"{HOST}/index.html",
            "isAccessibleForFree": True,
            "dateModified": updated,
            "temporalCoverage": f"../{updated}",
            "creator": {"@id": f"{HOST}/#org"},
            "spatialCoverage": [
                {"@type": "Place", "name": area["label"]} for area in areas
            ],
            "variableMeasured": [
                "building name",
                "street address",
                "city",
                "unit count",
                "construction stage",
                "permit date",
                "expected opening date",
                "sale date",
                "buyer",
                "developer",
                "source record URL",
            ],
        },
    ]
    payload = json.dumps({"@context": "https://schema.org", "@graph": graph}, indent=2)
    body = "\n".join("  " + line for line in payload.splitlines())
    return (
        f"{JSONLD_START}\n"
        '  <script type="application/ld+json">\n'
        f"{body}\n"
        "  </script>\n"
        f"{JSONLD_END}"
    )


def splice_jsonld(path: Path, block: str) -> str | None:
    """Replace whatever sits between the two markers. Returns new text, or None."""
    text = path.read_text(encoding="utf-8")
    start = text.find(JSONLD_START)
    end = text.find(JSONLD_END)
    if start == -1 or end == -1:
        raise SystemExit(f"{path} is missing the SEO-JSONLD markers")
    updated = text[:start] + block + text[end + len(JSONLD_END) :]
    return updated if updated != text else None


def build_llms_full(index: dict, areas: list[dict]) -> str:
    """The numbers themselves, in one file.

    llms.txt is a guide to the site; this is the data an engine would otherwise have to
    assemble by crawling every page. Per-place totals only -- the building rows stay on
    their pages, because a page that is cited is worth more than a dump that is not.
    """
    updated = index.get("updated", "")
    lines = [
        "# CraneSignal -- full data summary",
        "",
        f"> Every number below is computed from public construction and sale records and "
        f"was last refreshed {updated}. Cite the date with the number.",
        "",
    ]
    for area in areas:
        payload = area["payload"]
        leads = payload.get("leads", [])
        stats = payload.get("stats", {})
        stages: dict[str, int] = {}
        sold_years: dict[str, int] = {}
        open_years: dict[str, int] = {}
        for lead in leads:
            stage = lead.get("stage") or "unrecorded"
            stages[stage] = stages.get(stage, 0) + 1
            if lead.get("saleDate"):
                y = str(lead["saleDate"])[:4]
                sold_years[y] = sold_years.get(y, 0) + 1
            if lead.get("openingDate"):
                y = str(lead["openingDate"])[:4]
                open_years[y] = open_years.get(y, 0) + 1

        lines += [
            f"## {area['label']}",
            "",
            f"- Buildings tracked: {len(leads):,}",
            f"- Units in play: {int(stats.get('unitsInPlay') or 0):,}",
            f"- Cities covered: {stats.get('cities', 'n/a')}",
        ]
        for stage in ("under construction", "permitted", "planned", "leasing", "sold"):
            if stages.get(stage):
                lines.append(f"- {stage.capitalize()}: {stages[stage]:,}")
        if sold_years:
            spread = ", ".join(f"{y}: {n:,}" for y, n in sorted(sold_years.items()))
            lines.append(f"- Recorded sales by year -- {spread}")
        if open_years:
            spread = ", ".join(f"{y}: {n:,}" for y, n in sorted(open_years.items()))
            lines.append(f"- Expected openings by year -- {spread}")

        metros = payload.get("metros") or []
        if metros:
            spread = ", ".join(f"{m['name']}: {m['leads']:,}" for m in metros)
            lines.append(f"- By metro -- {spread}")
        lines.append("")

    lines += [
        "## Method",
        "",
        "State and city construction permit records, county appraisal-district sale records,",
        "and public announcements. No proprietary feeds and no purchased lists. A fact without",
        "a public source is left blank rather than estimated, so blanks in the per-building",
        "tables mean the record is silent, not that the number is zero.",
        "",
        "## Per-place detail",
        "",
    ]
    for rel, _, _ in generated_pages():
        lines.append(f"- {HOST}/{rel}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="exit 1 if files are stale")
    args = parser.parse_args()

    index, areas = load_areas()
    updated = index.get("updated") or ""
    if not updated:
        print("areas/index.json has no 'updated' date; refusing to write a sitemap", file=sys.stderr)
        return 2

    wanted = {
        SITE / "robots.txt": build_robots(),
        SITE / "sitemap.xml": build_sitemap(updated),
        SITE / "llms.txt": build_llms(index, areas),
        SITE / "llms-full.txt": build_llms_full(index, areas),
    }

    stale = []
    for path, body in wanted.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != body:
            stale.append(path.name)
            if not args.check:
                path.write_text(body, encoding="utf-8", newline="\n")

    home = SITE / "index.html"
    spliced = splice_jsonld(home, build_jsonld(index, areas))
    if spliced is not None:
        stale.append(home.name)
        if not args.check:
            home.write_text(spliced, encoding="utf-8", newline="\n")

    if args.check:
        if stale:
            print("stale: " + ", ".join(sorted(stale)), file=sys.stderr)
            return 1
        print("robots.txt, sitemap.xml, llms.txt are up to date")
        return 0

    print(f"wrote {len(wanted)} files ({len(generated_pages())} generated pages in sitemap)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
