use_default_settings: true
server:
  secret_key: "0a792bf1b5b1824453ce2217f94c8643626b22a3d5c7ec2c"
  limiter: false
  image_proxy: false
search:
  safe_search: 0
  formats: [html, json]
outgoing:
  request_timeout: 6.0
engines:
  - name: google
    disabled: false
  - name: bing
    disabled: false
  - name: duckduckgo
    disabled: false
  - name: brave
    disabled: false
